### ISSUE TITLE
[Task] Remove mandatory inclusion of empty `bamm:properties` and `bamm:operations`

### ISSUE THREAD

**Issue by atextor** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#105]
**Is your task related to a problem? Please describe.**
When an [Aspect is defined](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-aspects), it _must_ have a `bamm:properties` attribute and a `bamm:operations` attribute, even if the Aspect has no Properties or Operations. Both attributes take a list as input which may be empty.
Other than stating the obvious, having an attribute with an empty list has no benefits over not having the attribute at all.
The same holds true for the [`bamm:properties` list in Entities](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-entities) and the [`bamm:input` list in Opertations](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-operations).
The semantics (specification text and SHACL rules) should be changed so that leaving out the respective attribute is equivalent to it being present with the value of an empty list.

**Screenshots**
![image](https://user-images.githubusercontent.com/1199036/153141354-2d5fd2d0-92e1-4a79-8c82-40c02a8442b3.png)

**Additional context**
The current guideline does not contribute to a models expressiveness, but makes modeling unnecessarily verbose. This effect will be increased when #104 is implemented and `bamm:events` becomes yet another attribute of an Aspect: Then we would have three mandatory attributes with empty lists on an Aspect.

**Comment by janikps** [comment]
Should the Aspect have at leas one of properties or operations or events?
Is there any usage/example of aspect that have operations or event but no property at all?

BTW there is one more inconsistency at lest in the documentation:
[Attributes that all model elements have](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#attributes-that-all-model-elements-have) - each of them should be Required and not optional

**Comment by atextor** [comment]
The current specification [states that](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-aspects) must have the `bamm:properties` and the `bamm:operations` attributes*, but they can be empty, i.e., you can define an Aspect without any Properties or Operations. While it does not make much sense, there is no reason to disallow it. I am also allowed to define an empty Java class, a shell script without any statements or a JSON document without any keys (i.e. `{}`). I also see no good reason to change this.

Further, `bamm:description`, `bamm:preferredName` and `bamm:see` are optional for a reason; while it is certainly a good idea to have them (this should go in the "Best Practices", see #68), again there is not good reason to enforce this. While enforcing the presence of a description could make sense (although I wouldn't do it), enforcing `bamm:see` does not even make sense (not every model element has a meaninful reference to some outside definition) and enforcing `bamm:preferredName` does not make sense when the model element's local name is identical to what you would define as a preferred name.

\* `bamm:events` should be here also, see #104

**Comment by BirgitBoss** [comment]
Is it a backward compatible change? Is it forbidden to have an empty list in the envisioned model?

**Comment by atextor** [comment]
WG discussion 2022-02-24:
Question: Impact on payload? Answer: none.
Question: Is it forbidden to have an empty list in the envisioned model? Answer: No, this would still be allowed.
WG approves.
