### ISSUE TITLE
[BUG] RangeConstraint: Semantics for absence of bounds undefined

### ISSUE THREAD

**Issue by atextor** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#106]
**Describe the bug**
In the [definition for RangeConstraint](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/2.0.0-M1/characteristics.html#range-constraint), it is unclear what the semantics of the RangeConstraint is, if the optional `bamm-c:upperBoundDefinition` or `bamm-c:lowerBoundDefinition` are left out. The current sensible implementation in the SDK assumes the range as inclusive, i.e. the lower bound is not given it is assumed to be AT_LEAST and if the upper bound is not given it is assumed to be AT_MOST. This needs to be made explicit in the specification however.

**Where**
The [definition for RangeConstraint](https://openmanufacturingplatform.github.io/sds-documentation/bamm-specification/2.0.0-M1/characteristics.html#range-constraint)

**Screenshots**
![image](https://user-images.githubusercontent.com/1199036/153434088-837a3df7-5e01-4c3d-baad-2a0bfc3229b1.png)

**Comment by janikps** [comment]
In my opinion it is resolved by the last sentence of Range Constraint description:
"Restricts the value range of a Property. **At least one of** bamm-c:maxValue or bamm-c:minValue **must be present** in a Range Constraint. **By default both** bamm-c:maxValue and bamm-c:minValue **are inclusive**."

Possibly just move this to be the first sentence of description, not the last one, or highlight it in some other way.

**Comment by atextor** [comment]
Fixed by #130
