### ISSUE TITLE
[Task] Evolve `bamm:extends` and Abstract Entities into a full `bamm:refines` replacement

### ISSUE THREAD

**Issue by atextor** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#110]
## Summary
In #34, the `bamm:extends` keyword and the concept of Abstract Entities was introduced to replace the complicated `bamm:refines` construct. One of the places the `bamm:refines` feature was used in the scope of BAMM itself is the [Time Series Entity](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/entities.html#time-series-entity): As it is [currently described](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-time-series), the Time Series Entity has been transitioned into an Abstract Entity that only has the `timestamp` Property. Concrete Entities are supposed to extend the `bamm-e:TimeSeriesEntity` and add (at least one) value-carrying Property. However, the current state of the meta model does not allow to express this contract. Another place where this becomes obvious is the [Point3d](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/entities.html#point-3d) Entity, which had `x`, `y` and `z` Properties without a Characteristic, so that the Characteristic could be set when refining the Property. Turning Point3d into an Abstract Entity while still allowing a modeler to decide on the effective datatype of its Properties would yield only empty Abstract Entity, i.e. an Abstract Entity without any Properties.

Here are two possible ways that enable a modeler to express the contract "An Entity extending an Abstract Entity must specify a certain Property":

## Option 1. Introduce the concept of "Abstract Property".
* This would be similar to how an abstract class in Java (or other languages) can have abstract methods.
* An Abstract Property would be defined similar to how an Abstract Entity is defined:
   ```turtle
   :myAbstractProperty a bamm:AbstractProperty ;
   ...
   ```
* Only Abstract Entities can have Abstract Properties (i.e., Properties of Aspects and Entities can only ever be Entities, never Abstract Entities)
   ```turtle
   # Option 1: reuse bamm:properties
   :MyAbstractEntity a bamm:AbstractEntity ;
     bamm:properties ( :someProperty :myAbstractProperty ) .

   # Option 2: have a separate attribute for Abstract Properties:
   :MyAbstractEntity a bamm:AbstractEntity ;
      bamm:properties ( :someProperty ) ;
      bamm:abstractProperties ( :myAbstractProperty ) .
   ```
* Properties can extend an Abstract Property:
   ```turtle
   :myProperty a bamm:Property ;
      bamm:extends :myAbstractProperty ;
      ...
   ```
* An Entity that extends an Abstract Entity would must have a Property extending the corresponding Abstract Property for each Abstract Property in the Abstract Entity.

## Option 2: Parameterized Entities
This is conceptually equal to parameterized classes/types in UML, Java or C#: Point3d as an example could be defined like (using UML/Java syntax as pseudo-code): "Point3d<T>", then define Properties `x`, `y` and `z` with a `bamm:characteristic` of T. When extending a parameterized Abstract Entity, the Entity would have to set the "argument". The RDF/TTL syntax could look something like the following:
```turtle
:T1 a bamm:Argument .  # Name of this meta model element would have to be decided on

:MyAbstractEntity a bamm:AbstractEntity ;   # "abstract class MyAbstractEntity<T1>"
   bamm:argument :T1 ;
   bamm:properties ( :myAbstractProperty ) .

:myAbstractProperty a bamm:Property ;
   bamm:characteristic :T1 .

# Usage:
:MyIntCharacteristic a bamm:Characteristic ;
   bamm:dataType xsd:int .

:MyEntity a bamm:Entity ;
   bamm:extends [
      bamm:entity :MyAbstractEntity ;
      bamm:argument bamm:MyIntCharacteristic ;
   ] .
```
In this example, T1 is the named argument; it needs to be defined as a standalone model element so that it can be referenced from both the Abstract Entity and the Property.

## Describe the solution you'd like
One of the above options (on another, consistent option) needs to be decided on an implemented, so that the contract described in the summary of the issue can be expressed. Whatever option is used, the `bamm-e` Entities `TimeSeriesEntity` and `Point3d` need to be expressed using it.
Personally I have a slight preference for the first option, because it would reuse the already-existing `bamm:extends` in the same way it's already used for Entities. Furthermore, there are fewer corner cases to specify; one could argue that there is no good reason to limit the Argument construct to Abstract Entities but make it usable in other places as well (e.g., for abstracting away other things such as `bamm:dataType` or even `bamm:description`), which would increase complexity of the meta model and corresponding tooling considerably.

## Describe alternatives you've considered
The alternative that always remains is to not express the contract. But this would seriously limit the ability to build a catalog of reuseable Entities in a meaningful manner.

**Comment by BirgitBoss** [comment]
Alternative 1 seems to be more powerful than Alternative 2. We could even implement both because they complement each other.
However, for the beginning I also tend to prefer Alternative 1.

I personally would prefer not to be forced to decide immediately whether a property is abstract or not. This should be seen when defining it, not already in the list of properties.

:MyAbstractEntity a bamm:AbstractEntity ;
   bamm:properties ( :someProperty ) ;
   bamm:abstractProperties ( :myAbstractProperty ) .

==>

:MyAbstractEntity a bamm:AbstractEntity ;
   bamm:properties ( :someProperty :myAbstractProperty) ;

**Comment by chris-volk** [comment]
Alternative 2 poses great issues for implementing UI friendly in the Aspect Model Editor and will open up a lot of difficulties for a feature wise "closure" where everything is consistent

**Comment by kenwenzel** [comment]
I think the discussion here is related to [OWL (local) property restrictions](https://www.w3.org/TR/2012/REC-owl2-primer-20121211/#Property_Restrictions).

In OWL a property restriction could be defined as:
```turtle
:MyEntity a bamm:Entity ;
   rdfs:subClassOf [ owl:onProperty :myProperty; owl:allValuesFrom xsd:int ]
```
Either BAMM could simply use OWL's mechanisms to describe restrictions for properties or introduce something similar.

**Comment by atextor** [comment]
Both the previous `bamm:refines` and the proposed replacement mechanisms are more comparable to inheritance in object-oriented programming languages such as Java, rather than to restrictions in OWL. An abstract Entity in BAMM is comparable to an abstract Java class, in that it can/may not be instantiated directly. There is no comparable construct in OWL, because due to the open world assumption, you can always state `:myIndividual a :MyClass`, regardless of whether properties required by class restrictions are asserted - a reasoner will not complain.
What we try here is to add a way to specify a contract between the abstract Entity (i.e. superclass) and the extending Entity (i.e. subclass): "If you extend me, you will get a Property X, but you must specify X's characteristic.". So there needs to be a way for the abstract Entity to refer to some Property X _which does not have a Characteristic yet_ and is therefore no valid Property definition. In OWL, you'd build something like:
```turtle
# Assuming BAMM were built on OWL,
# and that a Property's Characteristic is set using `rdfs:range` (ignoring
# for the moment that Characteristics would have to be rdfs:Datatypes
# for scalar values and owl:Classes for Entity values...). Apart from a
# custom Annotation Property, this is the only way we could use in OWL to
# associate a Characteristic with the Property that not only works for scalar values
# (i.e. we could use rdfs:Datatypes as Characteristics for Properties with scalar values).
bamm:AbstractEntity a owl:Class .
bamm:Property rdfs:subPropertyOf owl:ObjectProperty .
bamm:Characteristic a owl:Class .

# Regular Property
:myProperty rdfs:subPropertyOf bamm:Property ;
  rdfs:range :MyCharacteristic .

# "Abstract" Property without a Characteristic
:myAbstractProperty rdfs:subPropertyOf bamm:Property .

:MyAbstractEntity rdfs:subClassOf bamm:Entity ;
  # Abstract Entity uses one abstract Property.
  # We make no statements about the Property's Characteristic, so this works.
  rdfs:subClassOf [
    a owl:Restriction ;
    owl:onProperty :myProperty ;
    owl:cardinality 1 ;
  ] ;
  # ... and one "regular" Property: Here we would have to specify that using the Property
  # in the Entity implies that the Property has a range defined - its Characteristic.
  rdfs:subClassOf [
    a owl:Restriction ;
    owl:onProperty :myAbstractProperty ;
    owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
    owl:onClass [
      a owl:Restriction ;
      owl:onProperty rdfs:range ;  # --> This does not work! rdfs:range is no OWL property.
          # If it were, the instance would have to have an assertion for its Characteristic...
      owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
      owl:onClass bamm:Characteristic ;
    ]
  ] .
```

So this does not work. The problem is two-fold: Firstly, the difficulty is not how to model the usage of the abstract Property, but how to define it. Secondly, even if we can work around it on the model level, we _do not want_ to do this, but solve this on the meta-model level so that building the corresponding model is as straightforward and as uncomplicated as possible.
