### ISSUE TITLE
[BUG] "Events" are missing from "Aspects" specification

### ISSUE THREAD

**Issue by thjaeckle** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#32]
**Describe the bug**
When having a look at the ["Aspects" specification](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html) I notices that "Events" are not mentioned at all, however they are part of the ["Meta Model Elements"](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/meta-model-elements.html).

**Where**
The ["Aspects" specification](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html)

**Screenshots**

**Additional context**

**Comment by atextor** [comment]
Hello Thomas,
you are correct, this needs to be addressed.
