### ISSUE TITLE
Introduce Entity inheritance

### ISSUE THREAD

**Issue by georgschmidtdumont** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#34]
**Is your task related to a problem? Please describe.**
It is not possible to define a hierarchy of Entities using the BAMM. One example where Entity inheritance would be useful might be an Aspect Model describing a List of Components required for a specific product.
Given the following definition for different Components
![components example](https://user-images.githubusercontent.com/34341958/121848286-2039bb00-ccea-11eb-9bb8-06a3c1ba6a8c.jpg)
it is not possible to define an Aspect Model where `Steeringwheel` and `Seat` are subclasses of `Component` and a List of `Component`s.

**Describe the solution you'd like**
The proposal is to introduce a new element `bamm:AbstractEntity` and a new attribute `bamm:extends` in BAMM to enable users to define inheritance on Entity level.
The Components example from above could then be defined as follows
```
:CarComponents a bamm:Aspect ;
   bamm:name "CarComponents" ;
   bamm:properties ( :components )

:components a bamm:Property ;
   bamm:name "components" ;
   bamm:characteristic [
      a bamm:List ;
      bamm:name "components " ;
      bamm:dataType :Component
   ] .

:Component a bamm:AbstractEntity ;
   bamm:name "Component" ;
   bamm:properties ( :typeNumber :manufacturer ) .

:SteeringWheel a bamm:Entity ;
   bamm:name "SteeringWheel " ;
   bamm:extends :Component ;
   bamm:properties ( :isMultifunction :airbag :horn  ) .

:Seat a bamm:Entity ;
   bamm:name "Seat" ;
   bamm:extends :Component ;
   bamm:properties ( :isElectric :material )
```
Meaning that the `Steeringwheel` and `Seat` entities contain the properties from the abstract `Component` entity as well as their own.
A payload conforming to this Aspect Model would look as follows
```
[
  {
    "typeNumber": 37465,
    "manufacturer": "Car Components Inc.",
    "isMultifunction": true ,
    "airbag": {},
    "horn": {}
  },
  {
    "typeNumber": 84375,
    "manufacturer": "Car Components Inc.",
    "isElectrical": false,
    "material": "fabric"
  }
]
```
The following validation rules are applied with regards to the `bamm:AbstractEntity` element and `bamm:extends` attribute
* an AbstractEntity may not be instantiated
* an Entity may extend either another Entity or an AbstractEntity
* an Entity may not extend more than one other Entity or AbstractEntity
* an Entity may not redefine a Property defined in the Entity or AbstractEntity it is extending
  * more specifically, all Properties defined in an Entity as well as in the Entity or AbstractEntity it is extending must have a unique name

**Describe alternatives you've considered**
The considered alternative, was to reuse the existing `bamm:refines` attribute.
The `bamm:refines` attribute is currently used to define a concept in an abstract manner and allow a specific use case to refine that concept for a specific need. An example where this is used is the `TimeSeries` Entity. In this case it is defined that a time-series is always structured such that it has a timestamp with a fixed definition and a value which is use case specific. Using `bamm:refines` it is possible to define the use case specific value according to the contract defined by the `TimeSeries` Entity.

However, the concept of refining an Entity is too complex. If, for example, a user wants to define multiple values in a time-series they need to encapsulate these values in an Entity since the `TimeSeries` Entity only allows one value Property. This is not intuitive. Additionally, having both the concept of refining an Entity as well as extending an Entity, will further complicate things.

Hence, the proposed solution should replace the existing concept of refining an Entity. The feature provided by `bamm:refines` can be covered by extending an Entity as well. Instead of defining, for example, the TimeSeries Entity as follows
```
bamm-e:TimeSeries a bamm:Entity ;
   bamm:properties ( bamm-e:timestamp bamm-e:value ) .

:ExampleTimeSeries bamm:refines bamm-e:TimeSeries ;
   bamm:properties ( :exampleValue ) .

:exampleValue bamm:refines bamm-c:value .
```
it can be defined using bamm:extends as follows
```
bamm-e:TimeSeries a bamm:AbstractEntity ;
   bamm:properties ( bamm-e:timestamp ) .

:ExampleTimeSeries a bamm:AbstractEntity ;
   bamm:extends bamm-e:TimeSeries ;
   bamm:properties ( :exampleValue ) .

:exampleValue a bamm:Property .
```

**Additional context**
[Declaring a Time Series](http://docs.digital-twin.bosch-nexeed.com/bamm-specification/1.6.0/modeling-guidelines.html#declaring-time-series)

**Comment by atextor** [comment]
First of all, thank you for the proposal.
I agree that Entity inheritance is useful and the described approach is reasonable. In addition, I think the approach is much easier to understand than the current `bamm:refines` modeling mechanics.

I think however that there are points that need to be clarified:

1. Consider the example above, a Collection of `Component`s. In the payload, JSON objects corresponding to any sub-Entity can appear in the array (or even payload corresponding to the parent Entity itself, if it isn't abstract). How is the payload deserializer supposed to know which type of Entity each object corresponds to? Let's assume we do not want to add meta-data to the payload just to designate the respective sub-Entity, because that is part of the core design of the payload mapping. Then the deserializer can take into account the differences between the sets of Properties each sub-Entity type has and use that to determine the type. In the example this is easy: If the object has `isMultifunction`, `airbag` and `horn` keys then it corresponds to the `SteeringWheel` Entity; if it has `isElectrical` and `material` keys, it corresponds to the `Seat` Entity. This decision needs to take into account the `payloadName` and `optional` of each Property, so for example, the following would have to be invalid:
    ```turtle
    :A a bamm:Entity ;
       bamm:extends :Component ;
       bamm:properties ( :prop1 [ bamm:property :prop2; bamm:optional true ] ) .

    :B a bamm:Entity ;
       bamm:extends :Component ;
       bamm:properties ( :prop1 ) .
    ```
    because encountering an object with just `prop1` set would be ambiguous. Likewise, the following would have to be invalid due to ambiguity caused by the payload name:
    ```turtle
    :A a bamm:Entity ;
       bamm:extends :Component ;
       bamm:properties ( [ bamm:property :prop1; bamm:payloadNamed "prop2" ] ) .

    :B a bamm:Entity ;
       bamm:extends :Component ;
       bamm:properties ( :prop2 ) .
    ```
    I think this works in practice, however, this mechanism needs to be properly specified and validated using the SHACL shapes.

2. Another point that is maybe even more complicated to solve: When considering the solution to the problem in bullet 1. and the differences between the sets of Properties of the different sub-Entities are compared, how exactly are the sub-Entities determined that should be considered in the first place? Taking all inheriting Entities defined in the current model file is clearly insufficient. Taking all Entities defined the current namespace would also only work if all Models referring to that namespace are present when validating the model. The problem here is that Aspect Models have a concept that is comparable to Java's package structure but nothing that compares to a class path. One solution might be a structure similar to a _Sealed Class_, i.e., when defining the `Component`, you must immediately enumerate all allowed sub-Entity types. This however clashes with "open" Entities like the `TimeSeriesEntity` where enumerating sub-Entities is impossible. I would like to hear your suggestion.

**Comment by georgschmidtdumont** [comment]
Hi @atextor, thanks for the feedback.

With regards to bullet 1., I will think about possibly further rules required to create a valid Aspect Model with the proposed changes.

With regards to bullet 2., IMHO all Entities used in the current Aspect Model need to be considered in order to have all information for a specific payload. During validation all these Entities are present since the Aspect Model is resolved before it is validated.

**Comment by georgschmidtdumont** [comment]
Hi @atextor,

with regards to bullet 1 in your [first comment](https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/issues/34#issuecomment-860510171) above, I believe implicitly the two cases are covered by the last validation rule specified in the task above. A more specific iteration of that rule could be defined by splitting the rule into two separate rules

1. all Properties defined in an Entity hierarchy must have a unique **payload name**
2. the combination of all Properties, incl. optional Properties, of an Entity hierarchy must be unique

This is a very restrictive definition allowing a first implementation not to worry about ambiguity. If required, a less restrictive approach may be considered in future should the requirement arise.

**Comment by georgschmidtdumont** [comment]
With regards to determining the scope of Entities to be considered for validation, I realize that determining all Entities used in an Aspect Model, by determining whether an Entity is connected to the Aspect through some path in the graph, is not sufficient.

In the context of this task, the namespace of the Aspect could be used as the scope. A separate task should be defined to further analyse how the scope may be determined.

**Comment by BirgitBoss** [comment]
I think not only entity extension would be useful but also aspect extensions. I am not sure this can be handled with the same approach. 

See for example Handling of Submodel Templates with an example of Wittenstein starting from a standardized aspect model for digital nameplate, then adding generic information for electrical motors and finally adding information specific for the product of the company (Minute 2:38: https://www.youtube.com/watch?v=aV2dA8ZY2v0)

**Comment by georgschmidtdumont** [comment]
Hi @BirgitBoss, I agree it might be useful to extend Aspect Models as well. IMHO this should definitely be a separate discussion/issue since I believe that the topic of extending Aspect Model is very complex and would need quite a bit of conceptual work before such a feature may be implemented.

**Comment by BirgitBoss** [comment]
Discussion OMP SDS 24th June 2021:
 can we have a look at the implementation/modelling without extends feature?
 can we really discuss it without looking how to extend aspect, operations, events etc.?

**Comment by BirgitBoss** [comment]
To answer the first part of the question: 

How would the example in comment #issue-920107974 look like without inheritance:

There is only an entity "CarComponent" with a superset of all properties any car components may have. All properties specific for a car component need to be defined as optional. Additionally an additional property names "category" might be added consisting of an enum, listing all the different car components allowed in the list.
What is missing and cannot be defined are rules like:
If CarComponent.category == SteeringWheel then the property CarComponent.isMultifunction is mandatory
a.s.o.

:CarComponents a bamm:Aspect;
    bamm:name "CarComponents";
    bamm:properties (:components);
    bamm:operations ();
    bamm:preferredName "CarComponents"@en.
:components a bamm:Property;
    bamm:name "components";
    bamm:preferredName "components"@en;
    bamm:characteristic :CarComponentsList;
    bamm:description "List of CarComponents, either SteeringWheels or Seats"@en.
:CarComponentsList a bamm-c:List;
    bamm:name "CarComponentsList";
    bamm:preferredName "CarComponentsList"@en;
    bamm:dataType :CarComponent;
    bamm:ordered "true"^^xsd:boolean;
    bamm:allowDuplicates "true"^^xsd:boolean.
:CarComponent a bamm:Entity;
    bamm:name "CarComponent";
    bamm:properties (:category :typeNumber :manufacturer :isMultifunction :airbag :horn :isElectric :material);
    bamm:preferredName "CarComponent"@en.
:category a bamm:Property;
    bamm:name "category";
    bamm:preferredName "category"@en;
    bamm:characteristic :CarComponentEnum.
:typeNumber a bamm:Property;
    bamm:name "typeNumber";
    bamm:preferredName "typeNumber"@en.
:manufacturer a bamm:Property;
    bamm:name "manufacturer";
    bamm:preferredName "manufacturer"@en.
:isMultifunction a bamm:Property;
    bamm:name "isMultifunction";
    bamm:preferredName "isMultifunction"@en;
    bamm:description "only for SteeringWheels"@en;
    bamm:optional "true"^^xsd:boolean.
:airbag a bamm:Property;
    bamm:name "airbag";
    bamm:preferredName "airbag"@en;
    bamm:description "only for SteeringWheels"@en;
    bamm:optional "true"^^xsd:boolean.
:horn a bamm:Property;
    bamm:name "horn";
    bamm:preferredName "horn"@en;
    bamm:description "only for SteeringWheels"@en;
    bamm:optional "true"^^xsd:boolean.
:isElectric a bamm:Property;
    bamm:name "isElectric";
    bamm:preferredName "isElectric"@en;
    bamm:description "only for Seats"@en;
    bamm:optional "true"^^xsd:boolean.
:material a bamm:Property;
    bamm:name "material";
    bamm:preferredName "material"@en;
    bamm:description "only for Seats"@en;
    bamm:optional "true"^^xsd:boolean.
:CarComponentEnum a bamm-c:Enumeration;
    bamm:name "CarComponentEnum";
    bamm:preferredName "CarComponentEnum"@en;
    bamm:description "category to select category of car component. Depending on category properties need to have values."@en;
    bamm:dataType xsd:string;
    bamm-c:values ("SteeringWheel" "Seat").

**Comment by georgschmidtdumont** [comment]
Hi @BirgitBoss,

thanks for the explanation! I agree, it would be possible to define a single Entity with lots of optional Properties. As you have pointed out, doing this leads to a vague Aspect Model on the one hand and an incomplete Aspect Model on the other. An additional point I would like to make is that it makes it quite hard to define and determine which Property describes which domain concept.

**Comment by georgschmidtdumont** [comment]
Discussion SDS Working Group 08. July

12 from 13 approved
1 abstantion

**Comment by georgschmidtdumont** [comment]
The corresponding PR has been approved and merged. Hence the issue will be closed.
