### ISSUE TITLE
Fix examples for Trait and Constraints

### ISSUE THREAD

**Issue by atextor** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#35]
**Describe the bug**
In section [Declaring Constraints](https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/modeling-guidelines.html#declaring-constraints) that demonstrates how to use `Trait` and `Constraint`, some of the examples are wrong. In the _LimitListNumber_ example, `bamm-c:baseCharacteristic` must not be part the respective Constraint, but of the enclosing Trait. In the _RegularExpressionConstraint_ example, the Constraint must not be used as a Characteristic itself, but as part of a Trait.

**Where**
See above

**Screenshots**
n/a

**Additional context**
n/a

**Comment by BirgitBoss** [comment]
see #39 I assume these are the examples you want to fix - or are there any additional examples to be fixed? If no, then we could close this issue.

**Comment by atextor** [comment]
Yes, #39 is what I was talking about here. Usually, the issue opened later is marked as a duplicate and closed, but since here the description in #39 is more detailed, I opt for closing this issue.

**Comment by atextor** [comment]
Duplicate of #39
