### ISSUE TITLE
Determine the scope for resolving extending Entities

### ISSUE THREAD

**Issue by georgschmidtdumont** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#36]
**Is your task related to a problem? Please describe.**
In the context of issue #34, the question was posed how to determine the scope of Entities to be considered for validation, and other interaction with an Aspect Model, when the Aspect Model contains Entities which extend other Entities.

Consider the following example
```
:CarComponents a bamm:Aspect ;
   bamm:name "CarComponents" ;
   bamm:properties ( :components )

:components a bamm:Property ;
   bamm:name "components" ;
   bamm:characteristic [
      a bamm:List ;
      bamm:name "components " ;
      bamm:dataType :Component
   ] .

:Component a bamm:AbstractEntity ;
   bamm:name "Component" ;
   bamm:properties ( :typeNumber :manufacturer ) .

:SteeringWheel a bamm:Entity ;
   bamm:name "SteeringWheel " ;
   bamm:extends :Component ;
   bamm:properties ( :isMultifunction :airbag :horn  ) .

:Seat a bamm:Entity ;
   bamm:name "Seat" ;
   bamm:extends :Component ;
   bamm:properties ( :isElectric :material )
```
The `SteeringWheel` and `Seat` Entities do not have a direct connection to the `CarComponents` Aspect. Hence, when resolving the elements used in the Aspect Model, these Entities would not be included should these Entities be defined in a separate file.
This question of scope not only arises when considering Aspect Models stored on a file system, but also when considering loading an Aspect Model from a triple store.

**Describe the solution you'd like**
The scope of model elements to be included by the Aspect Model Resolver could made explicit by introducing imports. Implicitly the Turtle file containing an Aspect Model already contains "imports". The prefixes are a list of all namespaces referenced by the Aspect Model. By considering the prefixes the Aspect Model Resolver could determine all namespaces which contain elements used in the current model.

Using the prefixes as imports ordinarily would not work in case of the `SteeringWheel` and `Seat` Entities above, since no prefix would be defined for these elements as they are not directly referenced in the graph of the `CarComponents` Aspect. The proposal is to also define a prefix for these elements and as such define the scope of namespaces to be considered when resolving extending Entities.

Though in principle all Entities required for a specific Aspect can now be resolved, the proposed solution does not work out of the box when storing Aspect Models in a triple store, since prefixes are not persisted in triple stores. However, the prefixes could be explicitly added to the Aspect node of the graph in the triple store.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by BirgitBoss** [comment]
Hi, Georg, can you please give an example of adding a prefix to SteeringWheel and Seat. I would say they already have a prefix (the same as Component in this example, but they could also have different prefixes). But I understand the problem that they would not be included when starting from the aspect.

Why not change the resolver to always include all entities of an entity that is extended - enhanced version: only if these extension are within the namespaces you want to consider?

So is you proposal to introduce explicit namespace import for aspects and not only implicit namespace import?

**Comment by georgschmidtdumont** [comment]
> 
> 
> Hi, @georgschmidtdumont , can you please give an example of adding a prefix to SteeringWheel and Seat. I would say they already have a prefix (the same as Component in this example, but they could also have different prefixes). But I understand the problem that they would not be included when starting from the aspect.
> 
> Why not change the resolver to always include all entities of an entity that is extended - enhanced version: only if these extension are within the namespaces you want to consider?
> 
> So is you proposal to introduce explicit namespace import for aspects and not only implicit namespace import?

Hi @BirgitBoss,
jip, the proposal is to introduce explicit namespace imports.

Extending the resolver to always include all extending Entities would not be enough since the resolver does not not know where to look for these Entities. The resolver uses the namespace(s) to determine where in the file system it should look for Model Elements. Without the imports the resolver would hence not know which locations need to be considered.
