### ISSUE TITLE
[BUG] Unclear what the "B" in BAMM stands for 

### ISSUE THREAD

**Issue by wrichter** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#37]
**Describe the bug**
It is not immediately obvious to a non-WG participant what the B in BAMM stands for (.AMM I suppose stands for Aspect Meta Model).

**Where**
Neither https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/blob/main/README.md nor https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/snapshot/index.html explain where the name comes from (or I am being blind).

**Screenshots**
n/a

**Additional context**
n/a

**Comment by FelixPe** [comment]
The B of the recursive acronym stands for BAMM.

**Comment by wrichter** [comment]
Neat, I like those :-) Would be worth mentioning that in the README.

**Comment by atextor** [comment]
You're both correct, it's an recursive acronym and it should be made more explicit.

**Comment by BirgitBoss** [comment]
Decision SDS WG 24th June 2021:
- add information on acronym to the README.md file
