### ISSUE TITLE
[Task] Add explicit chapter for "Trait" for consistency of structure

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#42]
**Is your task related to a problem? Please describe.**
Although Traits are explained they are not handled in a spearate chapter like the other elementes of the meta mode. For ease reading of the specifciation this should be aligned.

**Describe the solution you'd like**
New chapter "Traits" and move content w.r.t. traits to this chapter.

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by DvSmi** [comment]
Wouldn't it be easier to just rename the chapter "Declaring constraints" to something like "Declaring Constraints and Traits" as they are closely related and will stick together. The information inside of the chapters would otherwise contain mostly the same information.
