### ISSUE TITLE
[Task] Improve Namespace Spec

### ISSUE THREAD

**Issue by elchtestAtBosch** [OpenManufacturingPlatform/sds-bamm-aspect-meta-model#49]
**Is your task related to a problem? Please describe.**
During the concept for namespace whitelisting we noticed that namespaces are underspecified.

**Describe the solution you'd like**
Please specify namespaces to
- be lowercase and with that implicitly case insensitive
- have at least two parts. eg. com.bosch or io.openmanufacturion
- maybe also a min length?

**Describe alternatives you've considered**
- Namespaces being case insensitive. Namespaces would be normalized to lower case. Might introduce problems with case sensitive file systems.
- Namespaces being case sensitive. I.e. com.bosch is not equal to com.Bosch. This feels unintuitive.

**Additional context**
We are implementing a namespace whitelisting and thought about the uniqueness and ownership of namespaces.

**Comment by atextor** [comment]
WG discussion 2022-02-24: The namespaces _must_ always be lowercase. The PR should be adapted accordingly.

**Comment by atextor** [comment]
Fixed by #78
